apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    chart: 'istiod'
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.23.2
    helm:
      values: |
        global:
          imagePullPolicy: IfNotPresent
          logAsJson: true
          defaultPodDisruptionBudget:
            enabled: false
        pilot:
          deploymentLabels:
            app.kubernetes.io/part-of: istio-ambient
          podLabels:
            app.kubernetes.io/part-of: istio-ambient
          autoscaleEnabled: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            # cf.) https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars
            PILOT_ENABLE_AMBIENT: "true"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
