apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    # ref https://github.com/grafana/helm-charts/tree/main/charts/promtail/
    chart: 'promtail'
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.15.5 # application 2.9.3
    helm:
      version: v3
      releaseName: promtail
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
