apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observation
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: observation/manifests/overlays/aws
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: feature/issues120
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
