apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-apigateway
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: ''
    repoURL: https://charts.konghq.com
    targetRevision: 2.9.1
    chart: 'kong'
    helm:
      # https://github.com/Kong/charts
      parameters:
      - name: 'podAnnotations.dapr\.io/enabled'
        value: true
      - name: 'podAnnotations.dapr\.io/app-id'
        value: "serverless"
      - name: 'podAnnotations.dapr\.io/app-port'
        value: "8000"
      - name: 'image.repository'
        value: 'public.ecr.aws/nautible/nautible-kong-serverless'
      - name: 'image.tag'
        value: 'v0.1.5'
      - name: 'env.plugins'
        value: 'bundled, serverless'
      - name: 'env.pluginserver_names'
        value: 'serverless'
      - name: 'env.pluginserver_serverless_query_cmd'
        value: '/usr/local/bin/serverless -dump'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
