apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-apigateway
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  source:
    path: ''
    repoURL: https://charts.konghq.com
    targetRevision: 2.9.1
    chart: 'kong'
    helm:
      parameters:
        - name: 'image.repository'
          value: 'public.ecr.aws/nautible/nautible-kong-serverless'
        - name: 'image.tag'
          value: 'v0.1.4'
        - name: 'env.plugins'
          value: 'bundled, serverless'
        - name: 'env.pluginserver_names'
          value: 'serverless'
        - name: 'env.pluginserver_serverless_query_cmd'
          value: '/usr/local/bin/serverless -dump'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
