apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: serverless
  namespace: default
config:
  count: 300
  interval: 100
  backend:
  - target: /kong/
    health: /kong/healthz.html
    pubsub: kong-serverless-plugin
    topic: kong-root-request
plugin: serverless
