apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: serverless
  namespace: default
config:
  count: 300
  interval: 100
  backend:
  - target: /
    health: /
    pubsub: kong-serverless-plugin-pubsub
    topic: kong-serverless-plugin
plugin: serverless
