apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kong-ingress
  namespace: kong
upstream:
  slots: 10
  hash_on: none
  hash_fallback: none
  healthchecks:
    threshold: 25
    active:
      concurrency: 10
      healthy:
        http_statuses:
        - 200
        - 302
        interval: 0
        successes: 1
      http_path: "/"
      timeout: 30
      unhealthy:
        http_failures: 3
        http_statuses:
        - 429
        interval: 0
        tcp_failures: 3
        timeouts: 0
    passive:
      healthy:
        http_statuses:
        - 200
        successes: 1
      unhealthy:
        http_failures: 3
        http_statuses:
        - 429
        - 503
        tcp_failures: 3
        timeouts: 30
proxy:
  protocol: http
  path: /
  connect_timeout: 30000
  retries: 10
  read_timeout: 30000
  write_timeout: 30000
route:
  methods:
  - POST
  - GET
  regex_priority: 0
  strip_path: false
  preserve_host: true
  protocols:
  - http
  - https