apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: consumer-pubsub
  namespace: kong
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://user:<password>@keda-queue-rabbitmq.default.svc.cluster.local:5672"
  - name: durable
    value: "true"
