apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-keycloak
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nautible-plugin-secretstore
  target:
    name: secret-keycloak                # Secret Resource
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_USER           # SecretResource key
      remoteRef:
        key: nautible-plugin-keycloak    # SecretsManager Name
        property: user                   # SecretsManager key
    - secretKey: KEYCLOAK_PASSWORD       # SecretResource key
      remoteRef:
        key: nautible-plugin-keycloak    # SecretsManager Name
        property: password               # SecretsManager key
    - secretKey: DB_HOST                 # SecretResource key
      remoteRef:
        key: nautible-plugin-keycloak-db # SecretsManager Name
        property: host                   # SecretsManager key
    - secretKey: DB_USER                 # SecretResource key
      remoteRef:
        key: nautible-plugin-keycloak-db # SecretsManager Name
        property: user                   # SecretsManager key
    - secretKey: DB_PASSWORD             # SecretResource key
      remoteRef:
        key: nautible-plugin-keycloak-db # SecretsManager Name
        property: password               # SecretResource key
