 apiVersion: v1
 kind: ServiceAccount
 metadata:
   annotations:
     eks.amazonaws.com/role-arn: arn:aws:iam::${ACCOUNT_ID}:role/nautible-plugin-dev-auth-secret-access-role
   name: secret-keycloak
   namespace: keycloak
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-keycloak
  namespace: keycloak
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: secretstore
