 apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: secretstore
   namespace: keycloak
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-keycloak
  namespace: keycloak
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: secretstore
