apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: keycloak-secretsmanager
  namespace: keycloak
spec:
  provider:
    aws:
      # Nodeに付与している権限でのアクセス
      service: SecretsManager
      region: ap-northeast-1
