apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://aws.github.io/eks-charts/'
    targetRevision: 1.7.1
    chart: 'aws-load-balancer-controller'
    helm:
      parameters:
        - name: 'serviceAccount.create'
          value: 'true'
        - name: 'serviceAccount.name'
          value: 'aws-load-balancer-controller-sa'
        - name: 'clusterName'
          value: 'nautible-dev-cluster' #FIXME: clusterName
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true

