apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautible-app-ms-stock-batch
  namespace: argocd
spec:
  destination:
    namespace: nautible-app-ms
    server: https://kubernetes.default.svc
  project: application
  source:
    path: overlays/dev/
    repoURL: https://github.com/nautible/nautible-app-ms-stock-batch-manifest
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
