apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubernetes-external-secrets
    server: 'https://kubernetes.default.svc'
  source:
    chart: 'kubernetes-external-secrets'
    repoURL: 'https://external-secrets.github.io/kubernetes-external-secrets/'
    targetRevision: 8.5.1
    helm:
      releaseName: kubernetes-external-secrets
      parameters:
      - name: 'env.AWS_REGION'
        value:  'ap-northeast-1'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
