apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: nautible-plugin-secretstore
spec:
  provider:
    aws:
      # Nodeに付与している権限でのアクセス
      service: SecretsManager
      region: ap-northeast-1
