 apiVersion: v1
 kind: ServiceAccount
 metadata:
   annotations:
     eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/nautible-app-dev-app-secret-access-role
   name: secretstore
   namespace: nautible-app-ms
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-app-ms
  namespace: nautible-app-ms
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
      auth:
        jwt:
          serviceAccountRef:
            name: secretstore
