apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-secretsmanager
  namespace: nautible-app-ms
spec:
  provider:
    aws:
      # Nodeに付与している権限でのアクセス
      service: SecretsManager
      region: ap-northeast-1
