apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautible-app-ms-payment-bff
  namespace: argocd
spec:
  destination:
    namespace: nautible-app
    server: https://kubernetes.default.svc
  project: application
  source:
    path: 'bff/overlays/dev/'
    repoURL: https://github.com/nautible/nautible-app-ms-payment-manifest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautible-app-ms-payment-cash
  namespace: argocd
spec:
  destination:
    namespace: nautible-app
    server: https://kubernetes.default.svc
  project: application
  source:
    path: 'cash/overlays/dev/'
    repoURL: https://github.com/nautible/nautible-app-ms-payment-manifest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautible-app-ms-payment-convenience
  namespace: argocd
spec:
  destination:
    namespace: nautible-app
    server: https://kubernetes.default.svc
  project: application
  source:
    path: 'convenience/overlays/dev/'
    repoURL: https://github.com/nautible/nautible-app-ms-payment-manifest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautible-app-ms-payment-credit
  namespace: argocd
spec:
  destination:
    namespace: nautible-app
    server: https://kubernetes.default.svc
  project: application
  source:
    path: 'credit/overlays/dev/'
    repoURL: https://github.com/nautible/nautible-app-ms-payment-manifest
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
