apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: istio-controlplane
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  source:
    repoURL: https://github.com/nautible/nautible-infra
    targetRevision: HEAD
    path: 'ArgoCD/ecosystems/base/istio/istio-controlplane/base'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
