apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecosystem-root
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 'secrets/external-secrets/azure'
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
