apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-app-ms
  namespace: nautible-app-ms
spec:
  provider:
    azurekv:
      tenantId: ${TENANT_ID}
      vaultUrl: ${APP_MS_VAULT_URL}
      authSecretRef:
        clientId:
          name: external-secrets-azure-credentials
          key: clientid
        clientSecret:
          name: external-secrets-azure-credentials
          key: clientsecret
