apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: service-mesh/ambient/base/kiali/base
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: feature/ambient
  syncPolicy:
    automated:
      prune: true
