apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-networking
  namespace: argocd
spec:
  destination:
    namespace: bookinfo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 'app-bookinfo/networking/base'
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
