apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    # ref https://github.com/prometheus-community/helm-charts
    chart: 'prometheus'
    repoURL: https://prometheus-community.github.io/helm-charts/
    targetRevision: 25.20.1 # application v2.51.2
    helm:
      version: v3
      releaseName: prometheus
      values: |
        prometheus-pushgateway:
          enabled: false
        extraScrapeConfigs: |
          - job_name: 'node'
            metrics_path: /metrics
            static_configs:
              - targets:
                - prometheus-prometheus-node-exporter:9100
          - job_name: 'state'
            metrics_path: /metrics
            static_configs:
              - targets:
                - prometheus-kube-state-metrics:8080
          - job_name: 'quarkus'
            metrics_path: /q/metrics
            static_configs:
              - targets:
                - quarkus.default.svc.cluster.local:80
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
