apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - istio-base/application.yaml
  - istiod/application.yaml
  - istio-cni/application.yaml
  - ztunnel/application.yaml
  - istio-gateway/application.yaml
  #- istio-ingress/application.yaml
  #- istio-egress/application.yaml
