apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: kong-ingress-configuration
  namespace: kong
upstream:
  slots: 10
  hash_on: none
  hash_fallback: none
  healthchecks:
    threshold: 25
    active:
      concurrency: 10
      healthy:
        http_statuses:
          - 200
          - 302
        interval: 0
        successes: 1
      http_path: '/'
      timeout: 30
      unhealthy:
        http_failures: 3
        http_statuses:
          - 429
        interval: 0
        tcp_failures: 3
        timeouts: 0
    passive:
      healthy:
        http_statuses:
          - 200
        successes: 1
      unhealthy:
        http_failures: 3
        http_statuses:
          - 429
          - 503
        tcp_failures: 3
        timeouts: 30
