apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-demo-service
  namespace: default
  labels:
    serviceapp: demo-service
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      service: demo
  endpoints:
  - port: http
    interval: 30s
  namespaceSelector:
    matchNames:
    - default