apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # ServiceMonitor to monitor the Istio control plane and PodMonitor Envoy proxies
  # https://github.com/istio/istio/tree/master/samples/addons
  - istio-monitors.yaml
  # Federation using workload-level aggregated metrics
  # https://istio.io/latest/docs/ops/best-practices/observability/
  #- istio-federation.yaml
  - demo-service-servicemonitor.yaml
