apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-payment-service
  namespace: monitoring
  labels:
    serviceapp: payment-service
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nautible-app-ms-payment
  endpoints:
  - port: http
    interval: 30s
    path: /health
  namespaceSelector:
    matchNames:
    - nautible-app-ms