apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    # ref https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed
    chart: 'tempo-distributed'
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 1.2.7   # application v2.0.1
    helm: # minimum replicas and default storageClass
      version: v3
      releaseName: tempo
      # require ingester >= 2
      values: |
        ingester:
          replicas: 3
        metricsGenerator:
          enabled: true
        traces:
          otlp:
            http:
              enabled: true
            grpc:
              enabled: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
