apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitors
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: observation/monitors/base
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: feature/issues120
  syncPolicy:
    automated:
      prune: true
