apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-apigateway
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  source:
    path: kong-apigateway/manifests
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
