apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./alloy/config.yaml
  - ./prometheus/application.yaml
patches:
  - path: ./grafana/patch.yaml
  - path: ./loki/patch.yaml
