apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    # ref https://github.com/prometheus-community/helm-charts
    chart: 'prometheus'
    repoURL: https://prometheus-community.github.io/helm-charts/
    targetRevision: 25.20.1 # application v2.51.2
    helm:
      version: v3
      releaseName: prometheus
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
