apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    # ref https://github.com/grafana/loki/tree/main/production/helm/loki
    chart: 'loki'
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 5.44.4 # application v2.9.4
    helm: # minimum replicas and default storageClass
      version: v3
      releaseName: loki
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
