apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-node-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    # ref https://github.com/prometheus-community/helm-charts
    chart: 'prometheus-node-exporter'
    repoURL: https://prometheus-community.github.io/helm-charts/
    targetRevision: 4.32.0 # application 1.7.0
    helm:
      version: v3
      releaseName: prometheus-node-exporter
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
