apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: example-java
  namespace: nautible-app-ms
spec:
  exporter:
    endpoint: 'http://alloy.monitoring.svc.cluster.local:4318'
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: '1'
  java:
    env:
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_LOGS_EXPORTER
        value: none
      - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
        value: http/protobuf
      - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
        value: http/protobuf
