apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautible-kong-apigateway
  namespace: argocd
spec:
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kong-apigateway/overlays/aws
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
