apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kong-serverless-plugin-pubsub
  namespace: default
  labels:
    app.kubernetes.io/name: nautible-kong-apigateway
    app.kubernetes.io/instance: nautible-kong-apigateway
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: pubsub
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  type: pubsub.snssqs
  version: v1
  metadata:
  - name: region
    value: ap-northeast-1
  - name: disableEntityManagement
    value: "true"
