apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kong-apigatway-pubsub
  namespace: kong
  labels:
    app.kubernetes.io/name: kong-apigatway-pubsub
    app.kubernetes.io/instance: kong-apigatway-pubsub
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: pubsub
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  type: pubsub.snssqs
  version: v1
  metadata:
  - name: region
    value: ap-northeast-1
