---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws-credentials
  namespace: default
spec:
  secretTargetRef:
  - parameter: awsRoleArn    # The property in KEDA.
    name: secret-nautible-plugin-kong       # The name of the kubernetes secret.
    key: KONG_IAM_ARN        # The key from the kubernetes secret.
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-scaledobject
  namespace: default   # target application namespace
spec:
  scaleTargetRef:
    name: consumer     # target application name
  pollingInterval: 0   # Optional. Default: 30 seconds
  cooldownPeriod: 10   # Optional. Default: 300 seconds
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 3   # Optional. Default: 100
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-trigger-auth-aws-credentials
    metadata:
      queueURL: "kong-apigatway-pubsub"
      queueLength: "10"
      awsRegion: "ap-northeast-1"
