apiVersion: v1
kind: Secret
metadata:
  labels:
    alertmanager: main
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.22.2
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
    "global":
      "resolve_timeout": "5m"
      "slack_api_url": "http://demo-service1.default.svc.cluster.local:18080/alert"
    "receivers":
    - "name": "null"
    - "name": "slack"
    "slack_configs":
    - "channel": "#nautible"
    "route":
      "group_by":
      - "namespace"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "null"
      "repeat_interval": "12h"
      "routes":
      - "match":
          "severity": "critical"
        "receiver": "slack"
type: Opaque