apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crd
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 'observation/prometheus-operator/manifests/setup/'
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: feature/observation
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
