apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: observation/prometheus-operator/manifests/
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: feature/test_actions
  syncPolicy:
    automated:
      prune: false
    syncOptions:
      - CreateNamespace=true
