#
#   For AWS SystemManager
#   Githubをプライベートリポジトリで運用している場合に利用する
#
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: secret-github
  namespace: argocd
spec:
  backendType: systemManager
  data:
    - key: /nautible-infra/github/user   # SystemManager key
      name: github-user                   # Deployment name
    - key: /nautible-infra/github/token  # SystemManager key
      name: github-token                  # Deployment name
