apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: keda
    server: 'https://kubernetes.default.svc'
  source:
    chart: keda
    repoURL: 'https://kedacore.github.io/charts'
    targetRevision: 2.5.1
    helm:
      version: v3
      releaseName: keda
      parameters:
      - name: 'serviceAccount.annotations.eks\.amazonaws\.com\/role-arn'
        value: 'nautible-dev-AmazonEKSNodeRole'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
