apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: keda
    server: 'https://kubernetes.default.svc'
  source:
    chart: keda
    repoURL: 'https://kedacore.github.io/charts'
    targetRevision: 2.11.1
    helm:
      version: v3
      releaseName: keda
      # parameter https://github.com/kedacore/charts/blob/main/keda/values.yaml
      parameters:
      - name: 'operator.replicaCount'
        value: '1'
      - name: 'metricsServer.replicaCount'
        value: '1'
      - name: 'webhooks.enabled'
        value: 'true'
      - name: 'webhooks.replicaCount'
        value: '1'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
