apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: application-down-alert.rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus-operator
spec:
  groups:
  - name: rules-application-down-alert
    rules:
    - alert: ApplicationDown
      expr: >-
          count(kube_pod_status_phase{namespace="nautible-app-ms", phase=~"Failed|Pending|Unknown"} > 0) BY (namespace, pod, phase)
      for: 5m
      labels:
        severity: critical
      annotations:
        message: >-
          {{ $labels.pod }} pod in {{ $labels.namespace }} namespace are {{ $labels.phase }} status.
