apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: application-log-alert.rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus-operator
spec:
  groups:
  - name: rules-stock-alert
    rules:
    - alert: StockApplicationLogError
      expr: >-
          ( count (stock_log_error_total) > 0 ) or ( count (stock_log_severe_total) > 0 )
      for: 1m
      labels:
        severity: critical
      annotations:
        message: >-
          {{ $labels.job }}/{{ $labels.service }} targets in {{ $labels.namespace }} namespace are application error.
  - name: rules-customer-alert
    rules:
    - alert: CustomerApplicationLogError
      expr: >-
          ( count (customer_log_error_total) > 0 ) or ( count (customer_log_severe_total) > 0 )
      for: 1m
      labels:
        severity: critical
      annotations:
        message: >-
          {{ $labels.job }}/{{ $labels.service }} targets in {{ $labels.namespace }} namespace are application error.
  - name: rules-order-alert
    rules:
    - alert: OrderApplicationLogError
      expr: >-
          ( count (order_log_error_total) > 0 ) or ( count (order_log_severe_total) > 0 )
      for: 1m
      labels:
        severity: critical
      annotations:
        message: >-
          {{ $labels.job }}/{{ $labels.service }} targets in {{ $labels.namespace }} namespace are application error.
  - name: rules-product-alert
    rules:
    - alert: ProductApplicationLogError
      expr: >-
          ( count (product_log_error_total) > 0 ) or ( count (product_log_severe_total) > 0 )
      for: 1m
      labels:
        severity: critical
      annotations:
        message: >-
          {{ $labels.job }}/{{ $labels.service }} targets in {{ $labels.namespace }} namespace are application error.
  - name: rules-payment-alert
    rules:
    - alert: PaymentApplicationLogError
      expr: >-
          ( count (payment_log_error_total) > 0 ) or ( count (payment_log_severe_total) > 0 )
      for: 1m
      labels:
        severity: critical
      annotations:
        message: >-
          {{ $labels.job }}/{{ $labels.service }} targets in {{ $labels.namespace }} namespace are application error.
  - name: rules-payment-cache-alert
    rules:
    - alert: PaymentCacheApplicationLogError
      expr: >-
          ( count (payment_cache_log_error_total) > 0 ) or ( count (payment_cache_log_severe_total) > 0 )
      for: 1m
      labels:
        severity: critical
      annotations:
        message: >-
          {{ $labels.job }}/{{ $labels.service }} targets in {{ $labels.namespace }} namespace are application error.
  - name: rules-delivery-alert
    rules:
    - alert: DeliveryApplicationLogError
      expr: >-
          ( count (delivery_log_error_total) > 0 ) or ( count (delivery_log_severe_total) > 0 )
      for: 1m
      labels:
        severity: critical
      annotations:
        message: >-
          {{ $labels.job }}/{{ $labels.service }} targets in {{ $labels.namespace }} namespace are application error.
