apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Workload-level aggregation via recording rules
  # https://istio.io/latest/docs/ops/best-practices/observability/
  - istio-metrics-aggregation.yaml
  - demo-rule.yaml
  - customer-rule.yaml
  - stock-rule.yaml
  - order-rule.yaml
  - payment-rule.yaml
  - payment-credit-rule.yaml
  - product-rule.yaml
  - delivery-rule.yaml
