apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  source:
    helm:
      parameters:
      - name: 'env.AWS_REGION'
        value:  'ap-northeast-1'
