apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 'ArgoCD/ecosystems/base/istio/kiali/base'
    repoURL: https://github.com/nautible/nautible-infra
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
