apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    path: 'manifests/charts/gateways/istio-ingress'
    repoURL: 'https://github.com/istio/istio'
    targetRevision: 1.23.1
    helm:
      parameters:
        - name: 'global.hub'
          value: 'docker.io/istio'
        - name: 'global.tag'
          value: '1.23.1'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true