apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautible-app-examples-java
  namespace: argocd
spec:
  destination:
    namespace: nautible-app-examples
    server: https://kubernetes.default.svc
  project: examples
  source:
    path: nautible-app-examples-manifest-java/overlays/dev/
    repoURL: https://github.com/nautible/nautible-app-examples-manifest
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
