apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-app-ms
  namespace: argocd
spec:
  destination:
    namespace: nautible-app-ms
    server: https://kubernetes.default.svc
  project: application
  source:
    path: app-ms/overlays/aws/secret-parameter
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
