#
#   For AWS SecretsManager
#   Githubをプライベートリポジトリで運用している場合に利用する
#
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-github
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: nautible-app-ms-secretstore
  target:
    name: secret-github            # Secret Resource
    creationPolicy: Owner
  data:
    - secretKey: github-user       # SecretResource key
      remoteRef:
        key: nautible-infra-github # SecretsManager Name
        property: user             # SecretsManager key
    - secretKey: github-token      # SecretResource key
      remoteRef:
        key: nautible-infra-github # SecretsManager Name
        property: token            # SecretsManager key
