apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  source:
    helm: # use S3 strage
      parameters:
        - name: 'loki.auth_enabled'
          value: true
        - name: 'loki.commonConfig.replication_factor'
          value: 1
        - name: 'loki.bucketNames.chunks'
          value: 'nautible-plugin-dev-loki-ap-northeast-1'
        - name: 'loki.bucketNames.ruler'
          value: 'nautible-plugin-dev-loki-ap-northeast-1'
        - name: 'loki.bucketNames.admin'
          value: 'nautible-plugin-dev-loki-ap-northeast-1'
        - name: 'loki.storage.type'
          value: 's3'
        - name: 'loki.storage.s3.region'
          value: 'ap-northeast-1'
        - name: 'loki.write.replicas'
          value: 1
        - name: 'loki.read.replicas'
          value: 1
