apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    # ref https://github.com/grafana/loki/tree/main/production/helm/loki
    chart: 'loki'
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 5.44.4 # application v2.9.4
    helm: # minimum replicas and default storageClass
      version: v3
      releaseName: loki
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            bucketNames:
              chunks: nautible-plugin-dev-loki-ap-northeast-1
              ruler: nautible-plugin-dev-loki-ap-northeast-1
              admin: nautible-plugin-dev-loki-ap-northeast-1
            type: s3
            s3:
              region: ap-northeast-1
              s3ForcePathStyle: false
              insecure: false
          write:
            replicas: 1
          read:
            replicas: 1
        serviceAccount:
          create: true
          name: loki-sa
  #          annotations:
  #            arn:aws:iam::<ACCOUNT_ID>:role/nautible-plugin-dev-loki-bucket-role
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
