apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  source:
    helm: # minimum replicas and default storageClass
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          bucketNames:
            chunks: nautible-plugin-dev-loki-ap-northeast-1
            ruler: nautible-plugin-dev-loki-ap-northeast-1
            admin: nautible-plugin-dev-loki-ap-northeast-1
          storage:
            type: s3
            s3:
              region: ap-northeast-1
          write:
            replicas: 1
          read:
            replicas: 1
