apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    # ref https://github.com/grafana/loki/tree/main/production/helm/loki
    chart: 'loki'
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 4.8.0   # application v2.7.3
    helm:
      version: v3
      releaseName: loki
      values: |
        grobal:
          priorityClassName: daemonset-priority
        write:
          replicas: 1
        read:
          replicas: 1
          persistence:
            storageClass: Standard
        backend:
          replicas: 1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
