apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common/priorityclass.yaml
  - otel-operator/application.yaml
  - otel-collector/application.yaml
  - prometheus-operator/application.yaml
