apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patches:
- path: patch-java.json
  target:
    kind: Application
    name: nautible-app-examples-java
- path: patch-go.json
  target:
    kind: Application
    name: nautible-app-examples-go
