apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-common
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secret-app-ms
  target:
    name: secret-nautible-app-ms-common                         # Secret Resource
    creationPolicy: Owner
  data:
    - secretKey: SERVICE_BUS_CONNECTION_STRING                  # SecretResource key
      remoteRef:
        key: secret/nautible-app-ms-servicebus-connectionstring # KeyVault SecretName
