apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubernetes-external-secrets
    server: 'https://kubernetes.default.svc'
  source:
    # refs https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
    # refs https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
    chart: 'external-secrets'
    repoURL: 'https://charts.external-secrets.io/'
    targetRevision: 0.5.8
    helm:
      releaseName: kubernetes-external-secrets
      parameters:
        - name: 'envVarsFromSecret.AZURE_TENANT_ID.secretKeyRef'
          value: 'external-secrets-azure-credentials'
        - name: 'envVarsFromSecret.AZURE_TENANT_ID.key'
          value: 'tenantid'
        - name: 'envVarsFromSecret.AZURE_CLIENT_ID.secretKeyRef'
          value: 'external-secrets-azure-credentials'
        - name: 'envVarsFromSecret.AZURE_CLIENT_ID.key'
          value: 'clientid'
        - name: 'envVarsFromSecret.AZURE_CLIENT_SECRET.secretKeyRef'
          value: 'external-secrets-azure-credentials'
        - name: 'envVarsFromSecret.AZURE_CLIENT_SECRET.key'
          value: 'clientsecret'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
