apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: dapr-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://dapr.github.io/helm-charts/'
    targetRevision: 1.5.1
    chart: dapr
  ignoreDifferences:
  - group: apps
    kind: Secret
    name: dapr-trust-bundle
    namespace: dapr-system 
    jsonPointers:
    - /metadata/labels # デプロイ後に動的にラベル付与されるため差分を無視する
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: subscriptions.dapr.io
    namespace: dapr-system 
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/service/namespace # デプロイ後に動的に変更されるため差分を無視する
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
