apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    # ref https://github.com/grafana/helm-charts/tree/main/charts/grafana
    helm:
      values: |
        alloy:
          extraPorts:
            - name: 'grpc'
              port: 4317
              targetPort: 4317
              protocol: 'TCP'
            - name: 'http'
              port: 4318
              targetPort: 4318
              protocol: 'TCP'
          mounts:
            varlog: true
            dockercontainers: true
          configMap:
            create: false
            name: alloy-config
            key: config.alloy
