apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observation
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    path: observation/overlays/aws
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
