apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    # ref https://github.com/grafana/helm-charts/tree/main/charts/grafana
    helm:
      values: |
        persistence:
          type: pvc
          enabled: true
          storageClassName: gp2
          accessModes:
            - ReadWriteOnce
          size: 2Gi
          # annotations: {}
          finalizers:
            - kubernetes.io/pvc-protection
