apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: mimir-patch.yaml
  - path: loki-patch.yaml
  - path: alloy-patch.yaml
  - path: tempo-patch.yaml
