apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./mimir.yaml
  - ./tempo.yaml
  - ./kube-state-metrics.yaml
  - ./prometheus-node-exporter.yaml
patches:
  - path: grafana-patch.yaml
  - path: loki-patch.yaml
