apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: prometheus-patch.yaml
  - path: loki-patch.yaml
  - path: promtail-patch.yaml
  - path: tempo-patch.yaml
