apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    # ref https://github.com/grafana/loki/tree/main/production/helm/loki
    helm: # minimum replicas and default storageClass
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            bucketNames:
              chunks: nautible-plugin-dev-loki-ap-northeast-1
              ruler: nautible-plugin-dev-loki-ap-northeast-1
              admin: nautible-plugin-dev-loki-ap-northeast-1
            type: s3
            s3:
              region: ap-northeast-1
              s3ForcePathStyle: false
              insecure: false
        gateway:
          replicas: 1
        backend:
          replicas: 1
        write:
          replicas: 1
        read:
          replicas: 1
        lokiCanary:
          priorityClassName: daemonset-priority
        serviceAccount:
          create: false
          name: loki-sa
