apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    # ref https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed
    helm:
      values: |
        serviceAccount:
          create: false
          name: mimir-sa
        mimir:
          structuredConfig:
            common:
              storage:
                backend: s3
                s3:
                  bucket_name: nautible-plugin-dev-mimir-ap-northeast-1-tsdb
        store_gateway:
          replicas: 1
          priorityClassName: daemonset-priority
        minio:
          enabled: false
        distributor:
          replicas: 1
        ingester:
          replicas: 1
        overrides_exporter:
          replicas: 1
        ruler:
          enabled: false
        alertmanager:
          enabled: false
        querier:
          replicas: 1
        query_frontend: 
          replicas: 1
        query_scheduler:
          replicas: 1
        compactor:
          replicas: 1
        gateway:
          replicas: 1
        admin_api:
          replicas: 1

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
