---
# GrafanaLokiコンテナがS3にアクセスするためのServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::${ACCOUNT_ID}:role/nautible-plugin-dev-loki-bucket-role'
  name: loki-sa
  namespace: monitoring
---
# GrafanaTempoコンテナがS3にアクセスするためのServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::${ACCOUNT_ID}:role/nautible-plugin-dev-tempo-bucket-role'
  name: tempo-sa
  namespace: monitoring
---
# MimirコンテナがS3にアクセスするためのServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::${ACCOUNT_ID}:role/nautible-plugin-dev-mimir-bucket-role'
  name: mimir-sa
  namespace: monitoring
