apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    # ref https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed
    chart: 'tempo-distributed'
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 1.9.4 # application v2.4.1
    helm:
      version: v3
      releaseName: tempo
      values: |
        ingester:
          replicas: 2
        traces:
          otlp:
            http:
              enabled: true
            grpc:
              enabled: true
        distributor:
          receivers:
            otlp:
              protocols:
                grpc:
                http:
        serviceAccount:
          create: false
          name: tempo-sa
        storage:
          trace:
            backend: s3
            s3:
              bucket: nautible-plugin-dev-tempo-ap-northeast-1
              endpoint: s3.dualstack.ap-northeast-1.amazonaws.com
              region: ap-northeast-1
              insecure: false
              forcepathstyle: false
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
