#
#   For Azure key Vault
#   Githubをプライベートリポジトリで運用している場合に利用する
#
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: secret-github
  namespace: argocd
spec:
  backendType: azureKeyVault
  keyVaultName: nautibledevkeyvault
  data:
    - key: nautible-infra-github-user   # KeyVault key
      name: github-user                   # Deployment name
    - key: nautible-infra-github-token  # KeyVault key
      name: github-token                  # Deployment name