apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    chart: 'cni'
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.23.1
    helm:
      parameters:
        - name: 'profile'
          value: 'ambient'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
