apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer
  name: consumer
  namespace: kong
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: consumer
  type: ClusterIP
status:
  loadBalancer: {}
