---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    # ref https://github.com/open-telemetry/opentelemetry-helm-charts
    chart: 'opentelemetry-collector'
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts/
    targetRevision: 0.54.0 # last version kubernetes v1.23
    helm:
      version: v3
      values: |
        mode: daemonset
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          exporters:
            otlphttp:
              endpoint: http://tempo-distributor:4318
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: []
                exporters: [otlphttp]
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
