---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    # ref https://github.com/open-telemetry/opentelemetry-helm-charts
    chart: 'opentelemetry-collector'
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts/
    targetRevision: 0.51.2
    helm:
      version: v3
      values: |
        mode: daemonset
        priorityClassName: daemonset-priority
        config:
          receivers:
            jaeger:
              protocols:
                thrift_compact:
          processors:
            batch: {}
            memory_limiter: null
          exporters:
            logging:
              loglevel: debug
            otlp:
              endpoint: http://tempo-distributor:3100
          service:
            pipelines:
              traces:
                receivers: [jaeger]
                processors: [memory_limiter,batch]
                exporters: [otlp,logging]

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
