apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-app-ms
  namespace: nautible-app-ms
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-1
