apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
spec:
  destination:
    namespace: istio-ingress
    server: 'https://kubernetes.default.svc'
  source:
    chart: 'gateway'
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.23.1
    helm:
      parameters:
        - name: name
          value: istio-ingressgateway
        - name: service.type
          value: NodePort
        - name: service.allocateLoadBalancerNodePorts
          value: 'true'
        - name: service.ports[0].port
          value: '15021'
        - name: service.ports[0].targetPort
          value: '15021'
        - name: service.ports[0].name
          value: status-port
        - name: service.ports[0].protocol
          value: TCP
        - name: service.ports[1].port
          value: '80'
        - name: service.ports[1].targetPort
          value: '8080'
        - name: service.ports[1].name
          value: http2
        - name: service.ports[1].protocol
          value: TCP
        - name: service.ports[2].port
          value: '443'
        - name: service.ports[2].targetPort
          value: '8443'
        - name: service.ports[2].name
          value: https
        - name: service.ports[2].protocol
          value: TCP
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
