apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    # ref https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed
    chart: 'tempo-distributed'
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 1.9.0 # application v2.4.0
    helm: # minimum replicas and default storageClass
      version: v3
      releaseName: tempo
      values: |
        ingester:
          replicas: 1
        traces:
          otlp:
            http:
              enabled: true
            grpc:
              enabled: true
        distributor:
          receivers:
            otlp:
              protocols:
                grpc:
                http:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
