apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
spec:
  destination:
    namespace: istio-system
    server: 'https://kubernetes.default.svc'
  source:
    chart: 'cni'
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.23.2
    helm:
      values: |
        global:
          imagePullPolicy: IfNotPresent
          logAsJson: true
        cni:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 200m
            memory: 256Mi
          ambient:
            enabled: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
