apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-parameter
  namespace: argocd
spec:
  destination:
    namespace: nautible-app-ms
    server: https://kubernetes.default.svc
  project: application
  source:
    path: secrets/secret-parameter/azure
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
