apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-common
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secretstore-secretsmanager
  target:
    name: secret-nautible-app-ms-common             # secretsリソースの名前
    creationPolicy: Owner
  data:
    - secretKey: SERVICE_BUS_CONNECTION_STRING    # Deployment key
      remoteRef:
        key: secret/nautible-app-ms-order-dapr-statestore # SecretsManager key
