apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-common
  namespace: nautible-app-ms
spec:
  backendType: azureKeyVault
  keyVaultName: nautibledevkeyvault
  data:
    - key: nautible-app-ms-servicebus-connectionstring
      name: SERVICE_BUS_CONNECTION_STRING
