apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-cosmosdb
  namespace: nautible-app-ms
spec:
  backendType: azureKeyVault
  keyVaultName: nautibledevkeyvault
  data:
    - key: nautible-app-ms-cosmosdb-user
      name: DATABASE_USER
    - key: nautible-app-ms-cosmosdb-password
      name: DATABASE_PW
