apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-cosmosdb
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nautible-plugin-secretstore
  target:
    name: secret-nautible-app-ms-cosmosdb             # Secret Resource
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_USER                        # SecretResource key
      remoteRef:
        key: secret/nautible-app-ms-cosmosdb-user     # KeyVault SecretName
    - secretKey: DATABASE_PW                          # SecretResource key
      remoteRef:
        key: secret/nautible-app-ms-cosmosdb-password # KeyVault SecretName
