apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-cosmosdb
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore-secretsmanager
  target:
    name: secret-nautible-app-ms-cosmosdb             # secretsリソースの名前
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_USER    # Deployment key
      remoteRef:
        key: secret/nautible-app-ms-cosmosdb-user # SecretsManager key
    - secretKey: DATABASE_PW    # Deployment key
      remoteRef:
        key: secret/nautible-app-ms-cosmosdb-password # SecretsManager key
