apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-cosmosdb
  namespace: nautible-app
spec:
  backendType: azureKeyVault
  keyVaultName: nautibledevkeyvault
  data:
    - key: nautible-app-cosmosdb-user
      name: DATABASE_USER
    - key: nautible-app-cosmosdb-password
      name: DATABASE_PW
