#
#   For Azure key Vault
#   Githubをプライベートリポジトリで運用している場合に利用する
#
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-github
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: secretstore-secretsmanager
  target:
    name: secret-nautible-app-ms-order             # secretsリソースの名前
    creationPolicy: Owner
  data:
    - secretKey: github-user    # Deployment key
      remoteRef:
        key: secret/nautible-infra-github-user # SecretsManager key
    - secretKey: github-token    # Deployment key
      remoteRef:
        key: secret/nautible-infra-github-token # SecretsManager key
