apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-order
  namespace: nautible-app-ms
spec:
  backendType: azureKeyVault
  keyVaultName: nautibledevkeyvault
  data:
    - key: nautible-app-ms-order-dapr-statestore-host
      name: DAPR_STATESTORE_HOST
    - key: nautible-app-ms-order-dapr-statestore-password
      name: DAPR_STATESTORE_PW
