apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-product-db
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nautible-plugin-secretstore
  target:
    name: secret-nautible-app-ms-product-db             # secretsリソースの名前
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_USER    # Deployment key
      remoteRef:
        key: secret/nautible-app-ms-product-db-user # SecretsManager key
    - secretKey: DATABASE_PW    # Deployment key
      remoteRef:
        key: secret/nautible-app-ms-product-db-password # SecretsManager key
