apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-product-db
  namespace: nautible-app-ms
spec:
  backendType: azureKeyVault
  keyVaultName: nautibledevkeyvault
  data:
    - key: nautible-app-ms-product-db-user     # SystemManager key
      name: DATABASE_USER                      # Deployment key
    - key: nautible-app-ms-product-db-password # SystemManager key
      name: DATABASE_PW                        # Deployment key
