apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: alb
spec:
  scheme: internet-facing
  group: 
    name: nautible-alb-ingress
  subnets:
    matchTags:
      - key: Name
        values: ["nautible-dev-public-subnet"] # FIXME 対象のサブネットに変更する。(NAMEタグ名を指定する)