# 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argowf-restapi-sa
  namespace: nautible-app-ms
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argowf-restapi-role
  namespace: nautible-app-ms
rules:
- apiGroups: [""]
  resources: ["workflows.argoproj.io"]
  verbs: ["list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argowf-restapi-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argowf-restapi-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: argowf-restapi-sa
  namespace: nautible-app-ms
---
apiVersion: v1
kind: Secret
metadata:
  name: argowf-restapi-sa-token
  annotations:
    kubernetes.io/service-account.name: argowf-restapi-sa
type: kubernetes.io/service-account-token