apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  source:
    path: auth/overlays/azure
    repoURL: https://github.com/nautible/nautible-plugin
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
