apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-keycloak
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secret-keycloak
  target:
    name: secret-keycloak                                # Secret Resource
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_USER                           # SecretResource key
      remoteRef:
        key: secret/nautible-plugin-keycloak-user        # KeyVault SecretName
    - secretKey: KEYCLOAK_PASSWORD                       # SecretResource key
      remoteRef:
        key: secret/nautible-plugin-keycloak-password    # KeyVault SecretName
    - secretKey: DB_HOST                                 # SecretResource key
      remoteRef:
        key: secret/nautible-plugin-keycloak-db-host     # KeyVault SecretName
    - secretKey: DB_USER                                 # SecretResource key
      remoteRef:
        key: secret/nautible-plugin-keycloak-db-user     # KeyVault SecretName
    - secretKey: DB_PASSWORD                             # SecretResource key
      remoteRef:
        key: secret/nautible-plugin-keycloak-db-password # KeyVault SecretName
