apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - keycloak-secrets.yaml
patchesJson6902:
  # see base\keycloak-deploy.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: keycloak
    # fix value
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: http://localhost:8080/api/v1.0/nautible-auth/auth
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: http://localhost:3000
  # see base\keycloak-istio-auth.yaml
  - target:
      group: security.istio.io
      version: v1beta1
      kind: RequestAuthentication
      name: keycloak
    # fix value
    patch: |-
      - op: replace
        path: /spec/jwtRules/0/issuer
        value: http://localhost:8080/api/v1.0/nautible-auth/auth/realms/nautible-auth
  # see base\keycloak-istio-auth.yaml
  - target:
      group: security.istio.io
      version: v1beta1
      kind: AuthorizationPolicy
      name: keycloak
    # fix value
    patch: |-
      - op: replace
        path: /spec/rules/0/when/0/values
        value: ["http://localhost:8080/api/v1.0/nautible-auth/auth/realms/nautible-auth"]
  # see base\keycloak-istio-auth.yaml
  - target:
      group: kubernetes-client.io
      version: v1
      kind: ExternalSecret
      name: secret-keycloak
    patch: |-
      - op: add
        path: /spec/backendType
        value: azureKeyVault
      - op: add
        path: /spec/keyVaultName
        value: nautibledevkeyvault
  # TODO 外部公開するまでdevモードにする
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["start-dev","--import-realm","--hostname-strict=false","--db=postgres","--http-relative-path /auth"]
       