apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-keycloak
  namespace: keycloak
spec:
  provider:
    azurekv:
      tenantId: ${TENANT_ID} # 実行環境のテナントIDを設定
      vaultUrl: ${AUTH_VAULT_URL} # 実行環境のキーコンテナーのURIを設定
      authSecretRef:
        clientId:
          name: external-secrets-azure-credentials
          key: clientid
        clientSecret:
          name: external-secrets-azure-credentials
          key: clientsecret
