apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-root
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: 'ArgoCD/applications/overlays/azure'
    repoURL: https://github.com/nautible/nautible-infra
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
