apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- path: patch.json
  target:
    kind: Application
    name: nautible-app-ms-stock
- path: patch.json
  target:
    kind: Application
    name: nautible-app-ms-order
- path: patch.json
  target:
    kind: Application
    name: nautible-app-ms-customer
- path: patch_payment.json
  target:
    kind: Application
    name: nautible-app-ms-payment
- path: patch_credit.json
  target:
    kind: Application
    name: nautible-app-ms-payment-credit

# azure対応が完了したら以下の定義を削除して上記にパッチを追加する
- patch: |
    $patch: delete
    kind: dummy
    metadata:
      name: dummy
  target:
    kind: Application
    name: nautible-app-ms-product

