apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets-store
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - chart: secrets-store-csi-driver
            releaseName: secrets-store-csi-driver
            repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
            targetRevision: 1.4.8
            targetNamespace: kube-system
          - chart: secrets-store-csi-driver-provider-aws
            releaseName: secrets-store-csi-driver-provider-aws
            repoURL: https://aws.github.io/secrets-store-csi-driver-provider-aws
            targetRevision: 0.3.11
            targetNamespace: kube-system
  template:
    metadata:
      name: '{{releaseName}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        chart: '{{chart}}'
        targetRevision: '{{targetRevision}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{targetNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
