apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: 'https://kubernetes.default.svc'
  source:
    # refs https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
    # refs https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets
    chart: 'external-secrets'
    repoURL: 'https://charts.external-secrets.io/'
    targetRevision: 0.5.8
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true