#
#   For AWS SecretsManager
#   Githubをプライベートリポジトリで運用している場合に利用する
#
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-github
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secretstore-secretsmanager
  target:
    name: secret-github                # secretsリソースの名前
    creationPolicy: Owner
  data:
    - secretKey: nautible-infra-github # Deployment key
      remoteRef:
        key: user                      # SecretsManager key
    - secretKey: nautible-infra-github # Deployment key
      remoteRef:
        key: token                     # SecretsManager key
