apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secret-nautible-plugin-kong
  namespace: kong
spec:
  backendType: systemManager
  data:
    - key: kong-iam-arn
      name: KONG_IAM_ARN
