apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secret-nautible-plugin-kong
  namespace: default
spec:
  backendType: systemManager
  data:
    - key: nautible-plugin-kong-iam-arn
      name: KONG_IAM_ARN
