apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-order
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secretstore-secretsmanager
  target:
    name: secret-nautible-app-ms-order             # secretsリソースの名前
    creationPolicy: Owner
  data:
    - secretKey: DAPR_STATESTORE_PW                # Deployment key
      remoteRef:
        key: nautible-app-ms-order-dapr-statestore # SecretsManager key
        property: password
