apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-order
  namespace: nautible-app-ms
spec:
  backendType: systemManager
  data:
    - key: nautible-app-ms-order-elasticache-password
      name: ELASTICACHE_PW
