apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-order
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nautible-plugin-secretstore
  target:
    name: secret-nautible-app-ms-order             # Secret Resource
    creationPolicy: Owner
  data:
    - secretKey: DAPR_STATESTORE_PW                # SecretResource key
      remoteRef:
        key: nautible-app-ms-order-dapr-statestore # SecretsManager Name
        property: password                         # SecretsManager key
