apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-product-db
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secretstore-secretsmanager
  target:
    name: secret-nautible-app-ms-product-db # secretsリソースの名前
    creationPolicy: Owner
  data:
    - secretKey: nautible-app-ms-product-db # Deployment key
      remoteRef:
        key: user                           # SecretsManager key
    - secretKey: nautible-app-ms-product-db # Deployment key
      remoteRef:
        key: password                       # SecretsManager key
