apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-nautible-app-ms-product-db
  namespace: nautible-app-ms
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nautible-plugin-secretstore
  target:
    name: secret-nautible-app-ms-product-db # Secret Resource
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_USER              # SecretResource key
      remoteRef:
        key: nautible-app-ms-product-db     # SecretsManager Name
        property: user                      # SecretsManager key
    - secretKey: DATABASE_PW                # SecretResource key
      remoteRef:
        key: nautible-app-ms-product-db     # SecretsManager Name
        property: password                  # SecretsManager key
