apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    # ref https://github.com/grafana/alloy/tree/main/operations/helm/charts/alloy
    chart: 'alloy'
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 0.1.1 # application v1.0.0
    helm:
      version: v3
      releaseName: alloy
      values: |
        alloy:
          extraPorts:
            - name: 'grpc'
              port: 4317
              targetPort: 4317
              protocol: 'TCP'
            - name: 'http'
              port: 4318
              targetPort: 4318
              protocol: 'TCP'
          mounts:
            varlog: true
            dockercontainers: true
          configMap:
            create: false
            name: alloy-config
            key: config.alloy

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
