apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    # ref https://github.com/grafana/helm-charts/tree/main/charts/grafana
    chart: 'alloy'
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 0.1.1 # application v1.0.0
    helm:
      version: v3
      releaseName: alloy
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
